var astrologyPainters = {
  virgo: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(2,1);
    context.bezierCurveTo(2,1,5,2.634,5,6.414);
    context.bezierCurveTo(5,10.193999999999999,5,20,5,20);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(5,6);
    context.bezierCurveTo(5,4.2780000000000005,7.386,1,8.5,1);
    context.bezierCurveTo(9.614,1,12,4.684,12,6);
    context.bezierCurveTo(12,7.316,12,20,12,20);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(12,6);
    context.bezierCurveTo(12,4.2780000000000005,14.386,1,15.5,1);
    context.bezierCurveTo(16.614,1,19,4.684,19,6);
    context.bezierCurveTo(19,7.316,19,20,19,20);
    context.bezierCurveTo(19,23.813,21,25,21,25);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(19,11);
    context.bezierCurveTo(19,9.337,21.089,6,22,6);
    context.bezierCurveTo(22.911,6,24,9.077,24,12);
    context.bezierCurveTo(24,14.532,22.276,21.148,15,23);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  taurus: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(12.994,8.989);
    context.bezierCurveTo(20.962,8.989,17.951999999999998,0.9960000000000004,25,0.9960000000000004);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(13.006,8.989);
    context.bezierCurveTo(5.038,8.989,8.048,0.996,1,0.996);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.arc(13,17,8,0,6.283185307179586,true);
    context.closePath();
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  scorpio: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,1);
    context.bezierCurveTo(1,1,4,2.635,4,6.414);
    context.bezierCurveTo(4,10.193,4,20,4,20);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(4,6);
    context.bezierCurveTo(4,4.2780000000000005,6.386,1,7.5,1);
    context.bezierCurveTo(8.613,1,11,4.684,11,6);
    context.bezierCurveTo(11,7.316,11,20,11,20);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(25,23);
    context.bezierCurveTo(18.894,23,18,22.203,18,18);
    context.bezierCurveTo(18,18,18,7.316000000000001,18,6);
    context.bezierCurveTo(18,4.683999999999999,15.613,1,14.5,1);
    context.bezierCurveTo(13.386,1,11,4.278,11,6);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(23,21);
    context.lineTo(25,23);
    context.lineTo(23,25);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  sagittarius: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(13,1);
    context.lineTo(25,1);
    context.lineTo(25,13);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,25);
    context.lineTo(25,1);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(4,12);
    context.lineTo(14,22);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  pisces: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(21,1);
    context.bezierCurveTo(21,1,16.981,5.271,16.981,13.072);
    context.bezierCurveTo(16.981,20.872999999999998,21,25,21,25);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(5,1);
    context.bezierCurveTo(5,1,9.019,5.271,9.019,13.072);
    context.bezierCurveTo(9.019,20.872999999999998,5,25,5,25);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(5,13);
    context.lineTo(21,13);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  leo: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
context.strokeStyle = shape.fillColor;
context.translate(0,0);
context.translate(0,0);
context.beginPath();
context.moveTo(0,0);
context.lineTo(26,0);
context.lineTo(26,26);
context.lineTo(0,26);
context.closePath();
context.clip();
context.translate(0,0);
context.translate(0,0);
context.scale(1,1);
context.translate(0,0);
context.lineCap = 'butt';
context.lineJoin = 'miter';
context.miterLimit = 4;
context.save();
context.lineWidth = 2;
context.lineCap = "round";
context.lineJoin = "round";
context.miterLimit = 10;
context.beginPath();
context.arc(7,16,4,0,6.283185307179586,true);
context.closePath();
context.fill();
context.stroke();
context.restore();
context.save();
context.lineWidth = 2;
context.lineCap = "round";
context.lineJoin = "round";
context.miterLimit = 10;
context.beginPath();
context.moveTo(22.478,22.977);
context.bezierCurveTo(21.79,24.185,20.49,25,19,25);
context.bezierCurveTo(16.791,25,15,23.209,15,21);
context.fill();
context.stroke();
context.restore();
context.save();
context.lineWidth = 2;
context.lineCap = "round";
context.lineJoin = "round";
context.miterLimit = 10;
context.beginPath();
context.moveTo(11,16);
context.bezierCurveTo(11,13.218,9,12.146,9,7.5);
context.bezierCurveTo(9,3.91,11.91,1,15.5,1);
context.bezierCurveTo(19.09,1,22,3.91,22,7.5);
context.bezierCurveTo(22,13.698,15,16.423000000000002,15,21);
    context.fillStyle = '#000';
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  libra: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,22);
    context.lineTo(25,22);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(17.119,17.002);
    context.lineTo(25,17);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,17);
    context.lineTo(8.878,17);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(8.878,17);
    context.bezierCurveTo(6.555,15.775,5,13.547,5,11);
    context.bezierCurveTo(5,7.134,8.581,4,13,4);
    context.bezierCurveTo(17.418,4,21,7.134,21,11);
    context.bezierCurveTo(21,13.549,19.444,15.777999999999999,17.119,17.002);
    context.fillStyle = '#000';
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  gemini: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,1);
    context.bezierCurveTo(1,1,5.969,3.019,13.072,3.019);
    context.bezierCurveTo(20.174999999999997,3.019,25,1,25,1);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(25,25);
    context.bezierCurveTo(25,25,20.031,22.981,12.928,22.981);
    context.bezierCurveTo(5.825000000000003,22.981,1,25,1,25);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(18,23.289);
    context.lineTo(18,2.711);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(8,2.711);
    context.lineTo(8,23.289);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  capricorn: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.beginPath();
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,1);
    context.bezierCurveTo(1,1,4,2.635,4,6.414);
    context.bezierCurveTo(4,10.193,4,18,4,18);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(4,6);
    context.bezierCurveTo(4,4.2780000000000005,7.886,1,9,1);
    context.bezierCurveTo(10.113,1,14,2.815,14,6);
    context.bezierCurveTo(14,7.316,14,14,14,14);
    context.bezierCurveTo(14,19.211,16.606,22,21,22);
    context.bezierCurveTo(23.209,22,25,20.209,25,18);
    context.bezierCurveTo(25,15.791,23.209,14,21,14);
    context.bezierCurveTo(14.873000000000001,14,19.956,25,9,25);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  cancer: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.beginPath();
    context.translate(0,0);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.arc(20.5,10.5,4.5,0,6.283185307179586,true);
    context.closePath();
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(23.76,7.371);
    context.bezierCurveTo(23.76,7.371,19.868000000000002,3,12.583000000000002,3);
    context.bezierCurveTo(5.576,3,1,7,1,7);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.arc(5.5,15.5,4.5,0,6.283185307179586,true);
    context.closePath();
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(2.24,18.629);
    context.bezierCurveTo(2.24,18.629,6.132,23,13.417,23);
    context.bezierCurveTo(20.424,23,25,19,25,19);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  aries: function (shape, size, context) {
    context.save();
    setContext(shape,size,context);
    context.fillStyle = shape.fillColor;
    context.strokeStyle = shape.fillColor;
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.strokeStyle = 'rgba(0,0,0,0)';
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    //context.fillStyle = "rgba(0, 0, 0, 0)";
    //context.fillStyle = shape.fillColor;
    //context.strokeStyle = "#000000";
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(12.994,24.989);
    context.bezierCurveTo(12.994,22.03,14.16,0.9960000000000022,21,0.9960000000000022);
    context.bezierCurveTo(24.498,0.9960000000000022,25.02,4.017000000000002,25.02,4.017000000000002);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    //context.fillStyle = "rgba(0, 0, 0, 0)";
        //context.fillStyle = shape.fillColor;
    //context.strokeStyle = "#000000";
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(13.006,24.989);
    context.bezierCurveTo(13.006,22.03,11.84,0.996,5,0.996);
    context.bezierCurveTo(1.5019999999999998,0.996,0.9800000000000004,4.0169999999999995,0.9800000000000004,4.0169999999999995);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  },
  aquarius: function (shape, size, context) {
    context.save();
    setContext(shape,size,context,26,26);
    context.beginPath();
    context.moveTo(0,0);
    context.lineTo(26,0);
    context.lineTo(26,26);
    context.lineTo(0,26);
    context.closePath();
    context.clip();
    context.translate(0,0);
    context.translate(0,0);
    context.scale(1,1);
    context.translate(0,0);
    context.strokeStyle = 'rgba(0,0,0,0)';
    context.lineCap = 'butt';
    context.lineJoin = 'miter';
    context.miterLimit = 4;
    context.save();
    context.fillStyle = "rgba(0, 0, 0, 0)";
    context.fillStyle = shape.fillColor;
    context.strokeStyle = "#000000";
    context.strokeStyle = shape.fillColor;
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,10);
    context.bezierCurveTo(2,10,5,7,6,7);
    context.bezierCurveTo(7,7,8,10,9,10);
    context.bezierCurveTo(10,10,13,7,14,7);
    context.bezierCurveTo(15,7,16,10,17,10);
    context.bezierCurveTo(18,10,21,7,22,7);
    context.bezierCurveTo(23,7,24,10,25,10);
    context.fill();
    context.stroke();
    context.restore();
    context.save();
    context.fillStyle = "rgba(0, 0, 0, 0)";
    context.fillStyle = shape.fillColor;
    context.strokeStyle = "#000000";
    context.strokeStyle = shape.fillColor;
    context.lineWidth = 2;
    context.lineCap = "round";
    context.lineJoin = "round";
    context.miterLimit = 10;
    context.beginPath();
    context.moveTo(1,19);
    context.bezierCurveTo(2,19,5,16,6,16);
    context.bezierCurveTo(7,16,8,19,9,19);
    context.bezierCurveTo(10,19,13,16,14,16);
    context.bezierCurveTo(15,16,16,19,17,19);
    context.bezierCurveTo(18,19,21,16,22,16);
    context.bezierCurveTo(23,16,24,19,25,19);
    context.fill();
    context.stroke();
    context.restore();
    context.restore();
  }
}
